In [ ]:
function GENETIC-ALGORITHM (POPULATION) returns an individual
    inputs: POPULATION, a set of individuals given as chromosomes along with their
    fitness function values to be calculated
    for i = 1 to POPULATION.size do
        POPULATION[i].Fitness_Value = FITNESS-FUNCTION(POPULATION[I].Chromosome)
        repeat
        NEW-POPULATION ←empty set
        for i = 1 to (SIZE(population) / 2) do
            x ←RANDOM-SELECTION (POPULATION)
            y ←RANDOM-SELECTION(POPULATION)
            CHILD1 , CHILD2←REPRODUCE(x , y)
            if (small random probability) then CHILD1 ←MUTATE(child )
            if (small random probability) then CHILD2 ←MUTATE(child )
                add CHILD1 &amp; CHILD2 to NEW-POPULATION
                POPULATION ← NEW-POPULATION
            until some individual is fit enough, or enough time has elapsed
    return the best individual in population, according to FITNESS-FN and also the
    number of iterations

function FITNESS-FUNCTION(x) returns a fitness function value
    input: x is a chromosome in the POPULATION
    FITNESSVALUE = 0
    for i = 1 to 7
        for j = i+1 to 8
            if ( x[i] ≠ x[j] and ( | x[j] – x[i] | ≠ j – I )
            FITNESSVALUE = FITNESSVALUE + 1
    return FITNESSVALUE

function RANDOM-SELECTION (POPULATION) returns an individual
    input: POPULATION contains possible candidates for the reproduction
    Select POPULATION[ i ] with probability proportional to POPULATION[ i
    ].Fitness_Value

function REPRODUCE(x , y) returns an individual
    inputs: x , y, parent individuals
    n←LENGTH ( x ); c ← random number between 1 and n
    C1 = APPEND(SUBSTRING(x, 1, c), SUBSTRING(y, c + 1, n))
    C2 = APPEND(SUBSTRING(y, 1, c), SUBSTRING(x, c + 1, n))
    return C1 and C2

function MUTATE(x ) returns an individual
    n←LENGTH ( x ); c ← random number between 1 and n
    m ← a random number between 1 and 8 different from x[c]
    x[c] ← m
    return x

# Node based

In [1]:
import random
def generate_board_state():
    board_state = [random.randint(0, 7) for _ in range(8)]
    return board_state

ini = generate_board_state()
ini

def calculate_fitness(board):
    conflicts = 0
    for i in range(8):
        for j in range(i + 1, 8):
            if board[i] == board[j] or abs(board[i] - board[j]) == j - i:
                conflicts += 1
    return 28 - conflicts

calculate_fitness(ini)
def crossover(parent1, parent2):
    crossover_point = random.randint(1, 7)
    child = parent1[:crossover_point] + parent2[crossover_point:]
    return child
crossover(ini, ini)
def mutate(board_state):
    pos1, pos2 = random.sample(range(8), 2)
    board_state[pos1], board_state[pos2] = board_state[pos2], board_state[pos1]
    return board_state

mutate(ini)

def tournament_selection(population):
    tournament_size = 5
    tournament = random.sample(population, tournament_size)
    return max(tournament, key=lambda x: x[1])

population = [(generate_board_state(), 0) for _ in range(50)]
for generation in range(100):
    print(f"Iteration :- {generation + 1}")
    population = [(board_state, calculate_fitness(board_state)) for board_state, _ in population]
    
    print("Initial Population :-")
    for i, (board, fitness) in enumerate(population):
        print(f"Board {i+1}: {board}, Fitness: {fitness}")
    best_board_state = max(population, key=lambda x: x[1])[0]
    if calculate_fitness(best_board_state) == 28:
        print(f"Solution found in generation {generation}")
        break
    new_population = []
    new_population.append(max(population, key=lambda x: x[1]))
    
    print("Mutated Children :-")
    while len(new_population) < 50:
        parent1 = tournament_selection(population)
        parent2 = tournament_selection(population)
        child = crossover(parent1[0], parent2[0])
        child = mutate(child)
        child_fitness = calculate_fitness(child)  
        print(f"Child: {child}, Fitness: {child_fitness}")
        new_population.append((child, child_fitness))
    population = new_population
best_board_state

Iteration :- 1
Initial Population :-
Board 1: [2, 4, 6, 7, 4, 1, 2, 7], Fitness: 19
Board 2: [4, 4, 3, 6, 2, 3, 7, 7], Fitness: 21
Board 3: [7, 0, 5, 6, 6, 6, 3, 7], Fitness: 21
Board 4: [6, 7, 3, 6, 4, 1, 2, 1], Fitness: 17
Board 5: [5, 5, 0, 0, 3, 7, 1, 3], Fitness: 24
Board 6: [6, 1, 5, 2, 5, 3, 3, 5], Fitness: 22
Board 7: [1, 3, 2, 7, 5, 1, 0, 1], Fitness: 21
Board 8: [4, 5, 5, 6, 7, 4, 2, 4], Fitness: 18
Board 9: [2, 4, 1, 1, 1, 6, 6, 1], Fitness: 20
Board 10: [3, 7, 2, 1, 5, 7, 2, 3], Fitness: 22
Board 11: [3, 0, 2, 3, 6, 1, 6, 7], Fitness: 19
Board 12: [4, 2, 3, 5, 5, 4, 6, 2], Fitness: 19
Board 13: [4, 5, 2, 6, 1, 5, 2, 1], Fitness: 21
Board 14: [7, 4, 0, 6, 5, 1, 0, 7], Fitness: 23
Board 15: [1, 3, 4, 4, 3, 5, 0, 7], Fitness: 21
Board 16: [3, 3, 4, 0, 7, 2, 0, 3], Fitness: 19
Board 17: [1, 2, 3, 2, 4, 4, 7, 5], Fitness: 18
Board 18: [1, 6, 1, 7, 3, 5, 3, 4], Fitness: 22
Board 19: [5, 5, 7, 0, 7, 1, 1, 4], Fitness: 21
Board 20: [1, 5, 4, 1, 2, 4, 2, 3], Fitness: 20
Board 21: [2

[4, 6, 1, 5, 2, 0, 7, 3]

In [22]:
import random
import numpy as np


N_QUEENS = 8
POPULATION_SIZE = 100
MAX_GENERATIONS = 1000
MUTATION_RATE = 0.1

# Fitness function: Count non-conflicting pairs of queens
def fitness(chromosome):
    non_conflict_pairs = 0
    for i in range(len(chromosome)):
        for j in range(i + 1, len(chromosome)):
            if chromosome[i] != chromosome[j] and abs(chromosome[i] - chromosome[j]) != j - i:
                non_conflict_pairs += 1
    return non_conflict_pairs

# Generate initial population with the specific chromosome included
def generate_population(size, initial_chromosome):
    population = [initial_chromosome]
    while len(population) < size:
        population.append(random.sample(range(N_QUEENS), N_QUEENS))
    return population

# Selection using tournament method
def select(population):
    tournament = random.sample(population, k=5)
    return max(tournament, key=fitness)

# Crossover operation
def crossover(parent1, parent2):
    point = random.randint(1, N_QUEENS - 1)
    child = parent1[:point] + parent2[point:]
    return child

# Mutation operation
def mutate(chromosome):
    if random.random() < MUTATION_RATE:
        i = random.randint(0, N_QUEENS - 1)
        j = random.randint(0, N_QUEENS - 1)
        chromosome[i], chromosome[j] = chromosome[j], chromosome[i]

# Convert chromosome to matrix representation
def chromosome_to_matrix(chromosome):
    matrix = np.zeros((N_QUEENS, N_QUEENS), dtype=int)
    for col, row in enumerate(chromosome):
        matrix[row][col] = 1
    return matrix

# Main Genetic Algorithm
def genetic_algorithm(initial_chromosome):
    
    population = generate_population(POPULATION_SIZE, initial_chromosome)
    
    for generation in range(MAX_GENERATIONS):
        population = sorted(population, key=fitness, reverse=True)
        
        if fitness(population[0]) == (N_QUEENS * (N_QUEENS - 1)) // 2:
            print(f"Solution found in generation {generation}")
            solution = population[0]
            solution_matrix = chromosome_to_matrix(solution)
            print("Solution list:", solution)
            print("Solution matrix:")
            print(solution_matrix)
            return solution, solution_matrix
        
        new_population = []
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population)
            parent2 = select(population)
            child = crossover(parent1, parent2)
            mutate(child)
            new_population.append(child)
        
        population = new_population
    
    print("No solution found")
    return None, None

# Run the Genetic Algorithm with the initial chromosome [0, 1, 4, 3, 7, 6, 2, 5]
initial_chromosome = [0,1,2,3,4,5,6,7]
solution_list, solution_matrix = genetic_algorithm(initial_chromosome)
if solution_list is not None:
    print("Final solution list:", solution_list)
    print("Final solution matrix:")
    for i in solution_matrix:
        for j in i:
            if j==1:
                print("Q",end=" ")
            else:
                print(".",end=" ")
        print()
else:
    print("No valid solution found.")


Solution found in generation 13
Solution list: [3, 7, 0, 4, 6, 1, 5, 2]
Solution matrix:
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]]
Final solution list: [3, 7, 0, 4, 6, 1, 5, 2]
Final solution matrix:
. . Q . . . . . 
. . . . . Q . . 
. . . . . . . Q 
Q . . . . . . . 
. . . Q . . . . 
. . . . . . Q . 
. . . . Q . . . 
. Q . . . . . . 


In [24]:
import random
import numpy as np

# Constants
N_QUEENS = 8
POPULATION_SIZE = 100
MAX_GENERATIONS = 1000
MUTATION_RATE = 0.1

# Fitness function: Count non-conflicting pairs of queens
def fitness(chromosome):
    non_conflict_pairs = 0
    for i in range(len(chromosome)):
        for j in range(i + 1, len(chromosome)):
            if chromosome[i] != chromosome[j] and abs(chromosome[i] - chromosome[j]) != j - i:
                non_conflict_pairs += 1
    return non_conflict_pairs

# Generate initial population with the specific chromosome included
def generate_population(size, initial_chromosome):
    population = [initial_chromosome]
    while len(population) < size:
        population.append(random.sample(range(N_QUEENS), N_QUEENS))
    return population

# Selection using tournament method
def select(population):
    tournament = random.sample(population, k=5)
    return max(tournament, key=fitness)

# Crossover operation
def crossover(parent1, parent2):
    point = random.randint(1, N_QUEENS - 1)
    child = parent1[:point] + parent2[point:]
    return child

# Mutation operation
def mutate(chromosome):
    if random.random() < MUTATION_RATE:
        i = random.randint(0, N_QUEENS - 1)
        j = random.randint(0, N_QUEENS - 1)
        chromosome[i], chromosome[j] = chromosome[j], chromosome[i]

# Convert chromosome to matrix representation
def chromosome_to_matrix(chromosome):
    matrix = np.zeros((N_QUEENS, N_QUEENS), dtype=int)
    for col, row in enumerate(chromosome):
        matrix[row][col] = 1
    return matrix

# Main Genetic Algorithm
def genetic_algorithm(initial_chromosome):
    
    population = generate_population(POPULATION_SIZE, initial_chromosome)
    
    for generation in range(MAX_GENERATIONS):
        # Evaluate fitness of each individual
        population = sorted(population, key=fitness, reverse=True)
        
        # Print fitness of the best individual in the current generation
        best_fitness = fitness(population[0])
        print(f"Generation {generation}: Best fitness = {best_fitness}")
        
        if best_fitness == (N_QUEENS * (N_QUEENS - 1)) // 2:
            print(f"Solution found in generation {generation}")
            solution = population[0]
            solution_matrix = chromosome_to_matrix(solution)
            print("Solution list:", solution)
            print("Solution matrix:")
            print(solution_matrix)
            return solution, solution_matrix
        
        new_population = []
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population)
            parent2 = select(population)
            child = crossover(parent1, parent2)
            mutate(child)
            new_population.append(child)
        
        population = new_population
    
    print("No solution found")
    return None, None

# Run the Genetic Algorithm with the initial chromosome [7,6,5,4,3,2,1,0]
initial_chromosome = [7, 6, 5, 4, 3, 2, 1, 0]
solution_list, solution_matrix = genetic_algorithm(initial_chromosome)
if solution_list is not None:
    print("Final solution list:", solution_list)
    print("Final solution matrix:")
    for i in solution_matrix:
        for j in i:
            if j == 1:
                print("Q", end=" ")
            else:
                print(".", end=" ")
        print()
else:
    print("No valid solution found.")


Generation 0: Best fitness = 26
Generation 1: Best fitness = 26
Generation 2: Best fitness = 28
Solution found in generation 2
Solution list: [5, 2, 6, 3, 0, 7, 1, 4]
Solution matrix:
[[0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]]
Final solution list: [5, 2, 6, 3, 0, 7, 1, 4]
Final solution matrix:
. . . . Q . . . 
. . . . . . Q . 
. Q . . . . . . 
. . . Q . . . . 
. . . . . . . Q 
Q . . . . . . . 
. . Q . . . . . 
. . . . . Q . . 


# 8 Queens 

In [29]:
import random
import numpy as np

# Constants
N_QUEENS = 8
POPULATION_SIZE = 100
MAX_GENERATIONS = 1000
MUTATION_RATE = 0.1

# Fitness function: Count non-conflicting pairs of queens
def fitness(chromosome):
    non_conflict_pairs = 0
    for i in range(len(chromosome)):
        for j in range(i + 1, len(chromosome)):
            if chromosome[i] != chromosome[j] and abs(chromosome[i] - chromosome[j]) != j - i:
                non_conflict_pairs += 1
    return non_conflict_pairs

# Generate initial population with the specific chromosome included
def generate_population(size, initial_chromosome):
    population = [initial_chromosome]
    while len(population) < size:
        population.append(random.sample(range(N_QUEENS), N_QUEENS))
    return population

# Selection using tournament method
def select(population):
    tournament = random.sample(population, k=5)
    return max(tournament, key=fitness)

# Crossover operation
def crossover(parent1, parent2):
    point = random.randint(1, N_QUEENS - 1)
    child = parent1[:point] + parent2[point:]
    return child

# Mutation operation
def mutate(chromosome):
    if random.random() < MUTATION_RATE:
        i = random.randint(0, N_QUEENS - 1)
        j = random.randint(0, N_QUEENS - 1)
        chromosome[i], chromosome[j] = chromosome[j], chromosome[i]

# Convert chromosome to matrix representation
def chromosome_to_matrix(chromosome):
    matrix = np.zeros((N_QUEENS, N_QUEENS), dtype=int)
    for col, row in enumerate(chromosome):
        matrix[row][col] = 1
    return matrix

# Main Genetic Algorithm
def genetic_algorithm(initial_chromosome):
    
    population = generate_population(POPULATION_SIZE, initial_chromosome)
    
    for generation in range(MAX_GENERATIONS):
        # Evaluate fitness of each individual
        population = sorted(population, key=fitness, reverse=True)
        
        # Get the best individual and its fitness
        best_individual = population[0]
        best_fitness = fitness(best_individual)
        
        # Print fitness and best individual
        print(f"Generation {generation}: Best fitness = {best_fitness}, Best individual = {best_individual}")
        
        if best_fitness == (N_QUEENS * (N_QUEENS - 1)) // 2:
            print(f"Solution found in generation {generation}")
            solution_matrix = chromosome_to_matrix(best_individual)
            print("Solution list:", best_individual)
            print("Solution matrix:")
            print(solution_matrix)
            return best_individual, solution_matrix
        
        new_population = []
        while len(new_population) < POPULATION_SIZE:
            parent1 = select(population)
            parent2 = select(population)
            child = crossover(parent1, parent2)
            mutate(child)
            new_population.append(child)
        
        population = new_population
    
    print("No solution found")
    return None, None

# Run the Genetic Algorithm with the initial chromosome [7,6,5,4,3,2,1,0]
initial_chromosome = [0,1,2,3,4,5,6,7]
solution_list, solution_matrix = genetic_algorithm(initial_chromosome)
if solution_list is not None:
    print("Final solution list:", solution_list)
    print("Final solution matrix:")
    for i in solution_matrix:
        for j in i:
            if j == 1:
                print("Q", end=" ")
            else:
                print(".", end=" ")
        print()
else:
    print("No valid solution found.")


Generation 0: Best fitness = 27, Best individual = [5, 1, 0, 6, 3, 7, 2, 4]
Generation 1: Best fitness = 26, Best individual = [5, 1, 0, 6, 3, 7, 7, 4]
Generation 2: Best fitness = 27, Best individual = [5, 1, 0, 6, 3, 7, 2, 4]
Generation 3: Best fitness = 26, Best individual = [1, 7, 5, 3, 0, 4, 6, 4]
Generation 4: Best fitness = 27, Best individual = [5, 1, 0, 6, 3, 7, 2, 4]
Generation 5: Best fitness = 27, Best individual = [1, 7, 5, 3, 0, 7, 4, 2]
Generation 6: Best fitness = 28, Best individual = [1, 7, 5, 0, 2, 4, 6, 3]
Solution found in generation 6
Solution list: [1, 7, 5, 0, 2, 4, 6, 3]
Solution matrix:
[[0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]]
Final solution list: [1, 7, 5, 0, 2, 4, 6, 3]
Final solution matrix:
. . . Q . . . . 
Q . . . . . . . 
. . . . Q . . . 
. . . . . . . Q 
. . . . . Q . . 
. . Q . . . . . 
. . . . . . Q . 
. Q . . . . . . 
